import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "1.1", fontWeight: "600", letterSpacing: "0" }],
        "display-lg": ["56px", { lineHeight: "1.17", fontWeight: "500", letterSpacing: "0.2px" }],
        "heading-xl": ["24px", { lineHeight: "1.6", fontWeight: "500", letterSpacing: "0.2px" }],
        "heading-lg": ["22px", { lineHeight: "1.15", fontWeight: "500", letterSpacing: "0" }],
        "heading-md": ["20px", { lineHeight: "1.4", fontWeight: "500", letterSpacing: "0.2px" }],
        "heading-sm": ["18px", { lineHeight: "1.4", fontWeight: "500", letterSpacing: "0.2px" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400", letterSpacing: "0" }],
        "body-strong": ["16px", { lineHeight: "1.4", fontWeight: "500", letterSpacing: "0.2px" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400", letterSpacing: "0" }],
        "body-sm-strong": ["14px", { lineHeight: "1.6", fontWeight: "500", letterSpacing: "0.2px" }],
        "caption-md": ["13px", { lineHeight: "1.4", fontWeight: "400", letterSpacing: "0.1px" }],
        "caption-sm": ["12px", { lineHeight: "1.5", fontWeight: "400", letterSpacing: "0.4px" }],
        "link-md": ["16px", { lineHeight: "1.4", fontWeight: "500", letterSpacing: "0.3px" }],
        "button-md": ["14px", { lineHeight: "1.6", fontWeight: "500", letterSpacing: "0.2px" }],
      },
      colors: {
        canvas: "#07080a",
        surface: "#0d0d0d",
        "surface-elevated": "#101111",
        "surface-card": "#121212",
        "button-fg": "#18191a",
        ink: "#f4f4f6",
        body: "#cdcdcd",
        charcoal: "#d3d3d4",
        mute: "#9c9c9d",
        ash: "#6a6b6c",
        stone: "#434345",
        "on-dark": "#ffffff",
        "on-dark-mute": "rgba(255,255,255,0.72)",
        primary: "#ffffff",
        "primary-pressed": "#e8e8e8",
        "on-primary": "#000000",
        hairline: "#242728",
        "hairline-soft": "rgba(255,255,255,0.08)",
        "hairline-strong": "rgba(255,255,255,0.16)",
        "accent-blue": "#57c1ff",
        "accent-blue-soft": "rgba(87,193,255,0.15)",
        "accent-red": "#ff6161",
        "accent-red-soft": "rgba(255,97,97,0.15)",
        "accent-green": "#59d499",
        "accent-green-soft": "rgba(89,212,153,0.15)",
        "accent-yellow": "#ffc533",
        "accent-yellow-soft": "rgba(255,197,51,0.15)",
        "hero-stripe-start": "#ff5757",
        "hero-stripe-end": "#a1131a",
        "key-bg-start": "#121212",
        "key-bg-end": "#0d0d0d",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "10px",
        xl: "16px",
      },
      maxWidth: {
        content: "1240px",
        palette: "1080px",
      },
      spacing: {
        section: "96px",
      },
    },
  },
  plugins: [],
};

export default config;
