/**
 * Full life checklist (150 milestones).
 * `done: true` = checked off so far; `false` = still ahead.
 */
export type LifeChecklistItem = {
  id: string;
  emoji: string;
  label: string;
  done: boolean;
};

export const lifeChecklist: LifeChecklistItem[] = [
  { id: "born", emoji: "👶", label: "Be born", done: true },
  { id: "steps", emoji: "🚶‍", label: "Take first steps", done: true },
  { id: "words", emoji: "📣", label: "Say first words", done: true },
  { id: "read", emoji: "👨‍🏫", label: "Learn to read", done: true },
  { id: "friend", emoji: "🤗", label: "Make a friend", done: true },
  { id: "bike", emoji: "🚴‍", label: "Learn to ride a bike", done: true },
  { id: "book", emoji: "📗", label: "Read a book", done: true },
  { id: "swim", emoji: "🏊‍", label: "Learn to swim", done: true },
  { id: "elementary", emoji: "🏫", label: "Finish elementary school", done: true },
  { id: "sport", emoji: "⚽", label: "Play a sport", done: true },
  { id: "plane", emoji: "🛫", label: "Fly in a plane", done: true },
  { id: "boat", emoji: "🛥️", label: "Ride a boat", done: true },
  { id: "train", emoji: "🚆", label: "Ride in a train", done: true },
  { id: "helicopter", emoji: "🚁", label: "Ride a helicopter", done: true },
  { id: "ocean", emoji: "🌊", label: "See the ocean", done: true },
  { id: "snow", emoji: "❄️", label: "See snow", done: true },
  { id: "snowman", emoji: "☃️", label: "Make a snowman", done: true },
  { id: "middle-school", emoji: "🏫", label: "Finish middle school", done: true },
  { id: "concert", emoji: "🎶", label: "Go to a concert", done: true },
  { id: "camping", emoji: "🏕️", label: "Go camping", done: true },
  { id: "rollercoaster", emoji: "🎢", label: "Ride a rollercoaster", done: true },
  { id: "hackathon", emoji: "💻", label: "Attend my first hackathon (Tanda)", done: true },
  { id: "instrument", emoji: "🎻", label: "Play an instrument", done: true },
  { id: "credit-card", emoji: "💳", label: "Get a credit card", done: true },
  { id: "driving", emoji: "🚘", label: "Start driving", done: true },
  { id: "roadtrip", emoji: "🗺️", label: "Go on a roadtrip", done: true },
  { id: "country", emoji: "🗾", label: "Visit another country", done: true },
  { id: "speech", emoji: "🎤", label: "Give a speech", done: true },
  {
    id: "high-school",
    emoji: "🏫",
    label: "Graduate high school (Mansfield State High School, QCE)",
    done: true,
  },
  {
    id: "diploma",
    emoji: "📜",
    label: "Earn Diploma of Business (BSB50120)",
    done: true,
  },
  { id: "language", emoji: "🌐", label: "Learn another language", done: true },
  { id: "invest", emoji: "💸", label: "Invest some money", done: true },
  { id: "idol", emoji: "📷", label: "Meet an idol", done: true },
  { id: "mistake", emoji: "😭", label: "Make a terrible mistake", done: true },
  { id: "trophy", emoji: "🏆", label: "Win a trophy", done: true },
  { id: "mountain", emoji: "⛰️", label: "Climb a mountain", done: true },
  { id: "marathon", emoji: "🎽", label: "Run a marathon", done: true },
  { id: "cook", emoji: "🍳", label: "Learn to cook", done: true },
  { id: "cave", emoji: "🔦", label: "Explore a cave", done: false },
  { id: "volcano", emoji: "🌋", label: "See a volcano", done: false },
  {
    id: "start-university",
    emoji: "🎓",
    label: "Start university (QUT dual degree)",
    done: true,
  },
  { id: "yc", emoji: "🚀", label: "Enroll in Y Combinator Startup School", done: true },
  { id: "bop", emoji: "🏗️", label: "Join BOP Young Entrepreneurs Hub", done: true },
  { id: "tiber", emoji: "💡", label: "Create the TIBER framework", done: true },
  { id: "unpaste", emoji: "🤝", label: "Become technical cofounder at unpaste.ai", done: true },
  { id: "qut-tech", emoji: "🧑‍💻", label: "Secretary at QUT TECH", done: true },
  { id: "ship1p", emoji: "📈", label: "VC & community research at SH1P", done: true },
  { id: "chatstat", emoji: "🤖", label: "Build agentic AI systems at Chatstat (intern)", done: true },
  { id: "website", emoji: "🌐", label: "Ship this personal website", done: true },
  { id: "job", emoji: "🏢", label: "Get a job", done: true },
  { id: "promoted", emoji: "☝️", label: "Get promoted", done: true },
  { id: "paycheck", emoji: "💵", label: "Get a paycheck", done: true },
  { id: "fired", emoji: "🔥", label: "Get fired", done: false },
  { id: "news", emoji: "📰", label: "Get in the news", done: true },
  { id: "vote", emoji: "🗳️", label: "Vote in an election", done: true },
  { id: "careers", emoji: "🤡", label: "Switch careers", done: true },

  { id: "contract", emoji: "🖊️", label: "Sign a contract", done: false },
  { id: "house", emoji: "🏠", label: "Buy a house", done: false },
  { id: "kissed", emoji: "💋", label: "Get kissed", done: false },
  { id: "college", emoji: "🎓", label: "Graduate college", done: false },
  { id: "relationship", emoji: "💕", label: "Have a long relationship", done: false },
  { id: "dumped", emoji: "🗑️", label: "Get dumped", done: false },
  { id: "engaged", emoji: "💍", label: "Get engaged", done: false },
  { id: "married", emoji: "👰", label: "Get married", done: false },
  { id: "kid", emoji: "👶", label: "Have a kid", done: false },
  { id: "kid-walk", emoji: "🚶‍", label: "Teach your kid to walk", done: false },
  { id: "kid-talk", emoji: "📣", label: "Teach your kid to talk", done: false },
  { id: "kid-graduate", emoji: "🎓", label: "Watch your kid graduate", done: false },
  { id: "kid-married", emoji: "👰", label: "Watch your kid get married", done: false },
  { id: "grandparent", emoji: "👴", label: "Become a grandparent", done: false },
  { id: "retire", emoji: "🏖️", label: "Retire", done: false },
  { id: "story", emoji: "📔", label: "Tell your grandkid a story", done: false },
  { id: "eclipse", emoji: "🌑", label: "See a solar eclipse", done: false },
  { id: "garden", emoji: "🌷", label: "Plant a garden", done: true },
  { id: "world", emoji: "🌎", label: "Travel the world", done: false },
  { id: "first-app", emoji: "📱", label: "Ship your first app", done: true },
  { id: "github-100", emoji: "🐙", label: "Push 100 commits to GitHub", done: true },
  { id: "meetup", emoji: "🤝", label: "Attend a tech meetup", done: true },
  { id: "mentor", emoji: "🧭", label: "Find a mentor", done: true },
  { id: "mentor-someone", emoji: "🎓", label: "Mentor someone younger", done: false },
  { id: "open-source", emoji: "🌍", label: "Contribute to open source", done: true },
  { id: "side-project", emoji: "🛠️", label: "Launch a side project", done: true },
  { id: "first-customer", emoji: "💰", label: "Land your first paying customer", done: true },
  { id: "incorporate", emoji: "🏛️", label: "Incorporate a company", done: false },
  { id: "pre-seed", emoji: "🌱", label: "Raise a pre-seed round", done: false },
  { id: "series-a", emoji: "📈", label: "Raise a Series A", done: false },
  { id: "unicorn", emoji: "🦄", label: "Build a unicorn startup", done: false },
  { id: "exit", emoji: "🚪", label: "Sell or exit a company", done: false },
  { id: "demo-day", emoji: "🎤", label: "Pitch on demo day", done: false },
  { id: "yc-batch", emoji: "🟧", label: "Get into Y Combinator batch", done: false },
  { id: "conference-talk", emoji: "🎙️", label: "Give a conference talk", done: true },
  { id: "podcast", emoji: "🎧", label: "Appear on a podcast", done: false },
  { id: "newsletter-1k", emoji: "✉️", label: "Grow a newsletter to 1,000 subscribers", done: false },
  { id: "twitter-10k", emoji: "🐦", label: "Reach 10k followers on social", done: false },
  { id: "linkedin-viral", emoji: "💼", label: "Have a LinkedIn post go viral", done: false },
  { id: "hackathon-win", emoji: "🏅", label: "Win a hackathon", done: false },
  { id: "patent", emoji: "📋", label: "File a patent", done: false },
  { id: "research-paper", emoji: "📄", label: "Publish a research paper", done: false },
  { id: "thesis", emoji: "📚", label: "Write an honours thesis", done: false },
  { id: "deans-list", emoji: "⭐", label: "Make the Dean's List", done: false },
  { id: "study-abroad", emoji: "✈️", label: "Study abroad for a semester", done: false },
  { id: "intern-sf", emoji: "🌉", label: "Intern in San Francisco", done: false },
  { id: "intern-nyc", emoji: "🗽", label: "Intern in New York", done: false },
  { id: "intern-london", emoji: "🇬🇧", label: "Intern in London", done: false },
  { id: "remote-year", emoji: "🧳", label: "Work remotely from another country", done: false },
  { id: "digital-nomad", emoji: "💻", label: "Live as a digital nomad for 3 months", done: false },
  { id: "move-city", emoji: "🏙️", label: "Move to a new city", done: false },
  { id: "live-alone", emoji: "🔑", label: "Live alone for the first time", done: false },
  { id: "pet", emoji: "🐕", label: "Adopt a pet", done: false },
  { id: "plant-parent", emoji: "🪴", label: "Keep a plant alive for a year", done: true },
  { id: "blood-donate", emoji: "🩸", label: "Donate blood", done: false },
  { id: "organ-donate", emoji: "❤️", label: "Register as an organ donor", done: false },
  { id: "volunteer-100", emoji: "🤲", label: "Volunteer 100 hours", done: false },
  { id: "charity-raise", emoji: "🎗️", label: "Raise money for charity", done: false },
  { id: "5k", emoji: "🏃", label: "Run a 5K", done: false },
  { id: "10k", emoji: "🏃‍♂️", label: "Run a 10K", done: false },
  { id: "triathlon", emoji: "🏊", label: "Complete a triathlon", done: false },
  { id: "gym-100", emoji: "💪", label: "Work out 100 days in a row", done: false },
  { id: "meditate-30", emoji: "🧘", label: "Meditate for 30 days straight", done: true },
  { id: "skydive", emoji: "🪂", label: "Go skydiving", done: false },
  { id: "scuba", emoji: "🤿", label: "Get scuba certified", done: false },
  { id: "surf", emoji: "🏄", label: "Learn to surf", done: false },
  { id: "ski", emoji: "⛷️", label: "Learn to ski", done: false },
  { id: "hot-air", emoji: "🎈", label: "Ride a hot air balloon", done: false },
  { id: "northern-lights", emoji: "🌌", label: "See the northern lights", done: true },
  { id: "safari", emoji: "🦁", label: "Go on a safari", done: false },
  { id: "great-barrier", emoji: "🐠", label: "Snorkel the Great Barrier Reef", done: true },
  { id: "uluru", emoji: "🪨", label: "Visit Uluru", done: false },
  { id: "europe", emoji: "🇪🇺", label: "Backpack through Europe", done: false },
  { id: "asia", emoji: "🌏", label: "Travel through Asia", done: false },
  { id: "americas", emoji: "🌎", label: "Road trip the Americas", done: false },
  { id: "antarctica", emoji: "🐧", label: "Set foot in Antarctica", done: false },
  { id: "cruise", emoji: "🚢", label: "Take a cruise", done: true },
  { id: "hostel", emoji: "🛏️", label: "Stay in a hostel abroad", done: true },
  { id: "couchsurf", emoji: "🛋️", label: "Couchsurf in a stranger's home", done: false },
  { id: "festival", emoji: "🎪", label: "Attend a music festival", done: true },
  { id: "comedy-show", emoji: "😂", label: "See live stand-up comedy", done: true },
  { id: "broadway", emoji: "🎭", label: "See a Broadway-style show", done: false },
  { id: "escape-room", emoji: "🔐", label: "Beat an escape room", done: false },
  { id: "karaoke", emoji: "🎤", label: "Sing karaoke in public", done: false },
  { id: "cook-10", emoji: "👨‍🍳", label: "Cook a 10-course dinner for friends", done: false },
  { id: "wine-tasting", emoji: "🍷", label: "Go wine tasting", done: false },
  { id: "learn-dj", emoji: "🎛️", label: "DJ at a party", done: false },
  { id: "art-gallery", emoji: "🖼️", label: "Visit a world-famous museum", done: false },
  { id: "write-book", emoji: "📖", label: "Write a book", done: false },
  { id: "publish-book", emoji: "📕", label: "Publish a book", done: false },
  { id: "short-film", emoji: "🎬", label: "Make a short film", done: false },
  { id: "tedx", emoji: "🔴", label: "Give a TEDx talk", done: false },
  { id: "forbes-30", emoji: "📰", label: "Make a 30-under-30 list", done: false },
  { id: "time-magazine", emoji: "⏰", label: "Get featured in a major publication", done: true },
  { id: "aws-cert", emoji: "☁️", label: "Earn a cloud certification", done: true },
  { id: "hundred", emoji: "🎂", label: "Turn 100", done: false },
];

export const lifeChecklistDoneCount = lifeChecklist.filter((item) => item.done).length;
export const lifeChecklistTotalCount = lifeChecklist.length;
export const lifeChecklistRemainingCount = lifeChecklistTotalCount - lifeChecklistDoneCount;
